version: '3.8'

services:
  client:
    image: swolemate-client:v0.5.1
    container_name: swolemate-client
    ports:
      - "2470:2470"  # Frontend port
    networks:
      - cinelink_default
    restart: unless-stopped
    depends_on:
      - server
        
  server:
    image: swolemate-server:v0.5.4
    container_name: swolemate-server
    expose:  
      - 2469  # Backend port
    volumes:
      - ./logs:/app/logs
      - ./database:/app/database
      - ./server.env:/app/server.env
    networks:
      - cinelink_default
    restart: unless-stopped

volumes:
  database:
  logs:

networks:
  cinelink_default:
    external: true 