services:
  client:
    image: 192.168.31.233:5000/swolemate-client:latest
    container_name: swolemate-client
    ports:
      - "2470:2470"  # Frontend port
    restart: unless-stopped
    depends_on:
      - server

  server:
    image: 192.168.31.233:5000/swolemate-server:latest
    container_name: swolemate-server
    expose:
      - "2469" # Backend port (internal)
    working_dir: /data
    user: "1000:1000"
    volumes:
      - ./database:/data/database
      - ./backups:/data/backups
      - ./server.env:/data/server.env:ro
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    networks:
      default:
        aliases:
          - swolemate-server
